- name: This playbook is to deploy Travel India web application
  hosts: localhost
  become: yes

  tasks:
    - name: This block install apache2 web server and start the service
      block:
        - name: Install Apache web server
          apt:
            name: apache2
            state: present
            update_cache: yes

        - name: Start and enable Apache service
          service:
            name: apache2
            state: started
            enabled: yes
      tags: install-app

    - name: This block is to create directories and set permissions and deploy Travel India application
      block:
        - name: Create directory for Travel India web application
          file:
            path: /var/www/html/travel_india
            state: directory
            owner: www-data
            group: www-data
            mode: '0755'

        - name: Deploy Travel India web application files
          copy:
            src: index.html
            dest: /var/www/html/travel_india/index.html
            mode: '0644'

        - name: Create error directory for Travel India web application
          file:
            path: /var/www/html/travel_india/errors
            state: directory
            owner: www-data
            group: www-data
            mode: '0755'
          notify: reload apache

        - name: deploy error page for Travel India
          copy:
            src: error_404.html
            dest: /var/www/html/travel_india/errors/error_404.html
            mode: '0644'
          notify: reload apache

        - name: disable default apache site
          command: a2dissite 000-default.conf
          notify: reload apache

        - name: deploy apache config file for Travel India
          copy:
            src: apache.conf
            dest: /etc/apache2/sites-available/travel_india.conf
            mode: '0644'

        - name: enable apache config file for Travel India
          command: a2ensite travel_india.conf
          notify: reload apache

        - name: find the ip and map with domain name in /etc/hosts
          block:
          - name: Get primary IP address
            set_fact:
              server_ip: "{{ ansible_default_ipv4.address }}"
            
          - name: Add server IP to /etc/hosts with domain
            lineinfile:
              path: /etc/hosts
              line: "{{ server_ip }} travelindia.com www.travelindia.com"
              state: present
              create: no
      tags: install-app

    - name: uninstall the travel india app
      block:
        - name: Disable Travel India site
          command: a2dissite travel_india.conf
          notify: reload apache

        - name: Remove Travel India apache config file
          file:
            path: /etc/apache2/sites-available/travel_india.conf
            state: absent

        - name: Remove Travel India web application directory
          file:
            path: /var/www/html/travel_india
            state: absent
      tags: uninstall-app

    # - name: This block is to ensure firewall allows HTTP traffic
    #   block:
    #     - name: Allow HTTP traffic through UFW
    #       ufw:
    #         rule: allow
    #         name: 'Apache Full'

  handlers:
  - name: reload apache
    service:
      name: apache2
      state: reloaded

      
# command to run this playbook
# To install website: 
# ansible-playbook main.yml --tags "install-app"
# To uninstall website:  
# ansible-playbook main.yml --tags "uninstall-app"          

# check this website after installation:
# http://travelindia.com