- name: This playbook is to deploy UIT College web application
  hosts: localhost
  become: yes

  tasks:
    - name: This block install required web server and start the service
      block:
        - name: Install Apache web server
          apt:
            name: apache2
            state: present
            update_cache: yes

        - name: Start and enable Apache service
          service:
            name: apache2
            state: started
            enabled: yes

    - name: This bloock is to create directories and set permissions and deploy application
      block:
        - name: Create directory for UIT College web application
          file:
            path: /var/www/html/uit_college
            state: directory
            owner: www-data
            group: www-data
            mode: '0755'

        - name: Deploy UIT College web application files
          copy:
          file: